### ISSUE TITLE
Issue with latest Unity version 2021.3.6f1

### ISSUE THREAD

**Issue by SynthKittenDev** [sketchfab/unity-plugin#18]
Hi there,

Upon installing this plugin on Unity 2021.3.6f1, I get this error. I have tried this in a fresh 3D template, 3D URP template and 3D HDRP template. The same error in them all.

I'm certain it's due to a new Newtonsoft.Json version, but I don't know how to roll back to 12.0.0.

![Screenshot_15](https://user-images.githubusercontent.com/56303691/179639973-5ac905da-03b2-4b18-8d07-3f5a51202f3e.png)
0

**Comment by VoxelChunk** [comment]
You can find the fix for this [Here](https://github.com/sketchfab/unity-plugin/releases/tag/1.2.1), I just fixed it myself thanks to another post down in the forums a bit.

**Comment by SynthKittenDev** [comment]
> You can find the fix for this [Here](https://github.com/sketchfab/unity-plugin/releases/tag/1.2.1), I just fixed it myself thanks to another post down in the forums a bit.

Hi there, this version doesn't work for me either because it's a different error then the others people were having.

I believe it is due to the fact newtonsoft has updated in this version of Unity and the Sketchfab plugin can't use it since it's not the correct 12.0.0.0 version. Older releases haven't fixed it for me.

I get the same errors:
![Screenshot_16](https://user-images.githubusercontent.com/56303691/179762447-88ab2815-1371-46ba-b19d-59e58cf81e63.png)

**Comment by EmreErdogan** [comment]
I have the same issue with Unity 2021.3.7f1 on macOS Monterey 12.2.1 and SketchfabForUnity-v1.2.2

<img width="1114" alt="Screen Shot 2022-07-31 at 14 28 55" src="https://user-images.githubusercontent.com/2360385/182024140-9820a781-d14f-4999-b1ff-1cc053fe9b0c.png">

**Comment by endasil** [comment]
I downloaded the source code from https://github.com/sketchfab/UnityGLTF.git, swapped out the newtonsoft 12 dll in the GLTFSerialization project for 13, build the dll and replaced the old one and got it to work in 2021.3.7. If you want you can grab my package see if it works for you.

https://github.com/endasil/SketchfabForUnityUsingNewtonSoft13/raw/main/SketchfabForUnityUsingNewtonSoft13.unitypackage

**Comment by tkd-itsuki** [comment]
@endasil 
It worked. You should create a pull request for this fix to help everyone using unity 2021.

**Comment by endasil** [comment]
I do not have access to push to that repo, so I can't do that sadly.

**Comment by TWiG-US420** [comment]
this fixed it ... thank you

**Comment by FasihKhan1** [comment]
Assets\Sketchfab For Unity\Scripts\Resizer.cs(102,7): error CS1061: 'Texture2D' does not contain a definition for 'Reinitialize' and no accessible extension method 'Reinitialize' accepting a first argument of type 'Texture2D' could be found (are you missing a using directive or an assembly reference?)

**Comment by FasihKhan1** [comment]
My problem

**Comment by endasil** [comment]
What unity version are you using?
